pull_request_rules:
  - name: Automatic merge
    conditions:
      - author=scalameta-bot
      - check-success=Scalafmt
      - check-success=Website
      - check-success=Windows
      - check-success="'++2.12.12! testAllNonNative' 11"
      - check-success="'++2.12.20 test' 11"
      - check-success="'++2.13.17 test' 11"
      - check-success="'++3.3.6 test' 11"
      - check-success="scripted 11"
      - check-success="'++2.12.12! testAllNonNative' 17"
      - check-success="'++2.12.20 test' 17"
      - check-success="'++2.13.17 test' 17"
      - check-success="'++3.3.6 test' 17"
      - check-success="scripted 17"
    actions:
      merge:
        method: merge
