pull_request_rules:
  - name: Automatic merge
    conditions:
      - author=scalameta-bot
      - check-success=Scalafmt
      - check-success=Website
      - check-success=Windows
      - check-success="'++2.12.12! test' adopt@1.11"
      - check-success="'++2.12.19 test' adopt@1.11"
      - check-success="'++2.13.14 test' adopt@1.11"
      - check-success="'++3.3.3 test' adopt@1.11"
      - check-success="scripted adopt@1.11"
      - check-success="'++2.12.12! test' 17"
      - check-success="'++2.12.19 test' 17"
      - check-success="'++2.13.14 test' 17"
      - check-success="'++3.3.3 test' 17"
      - check-success=scripted 17
    actions:
      merge:
        method: merge
