<meta name="lang:clipboard.copy" content="Copy to clipboard">
<meta name="lang:clipboard.copied" content="Copied to clipboard">
<meta name="lang:search.result.none" content="No matching documents">
<meta name="lang:search.result.one" content="1 matching document">
<meta name="lang:search.result.other" content="# matching documents">
<meta name="lang:search.languages" content="">
<meta name="lang:search.tokenizer" content="$page.properties.("material.search.tokenizer"); null="[\\s\\-]+"$">
